server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver # org.gjt.mm.mysql.Driver也可
    url: jdbc:mysql://localhost:3306/db2021?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1234

eureka:
  client:
    #其实默认为true，可以不设置，表示是否将自己注册进EurekaServer
    register-with-eureka: true
    #默认为true，是否从EurekaServer抓取已有注册中心，单节点可以不用，集群一定要为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001 #修改服务名称
    prefer-ip-address: true #访问路径可以显示IP地址
    #Eureka客户端向服务端发送心跳的实际间隔，单位为秒（默认为30秒）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端收到最后一次心跳后等待时间上线，单位为秒（默认为90秒） 超时将剔除服务
    lease-expiration-duration-in-seconds: 2

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml       #sql映射文件位置
  type-aliases-package: com.mmd.springcloud.entity     #起别名
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰式命名


logging:
  level:
    com.mmd.springcloud.mapper: debug


