server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  #consul注册中心地址
  cloud:
    consul:
      host: localhost #默认也是localhost
      port: 8500  #默认就是8500
      discovery:
        service-name: ${spring.application.name} #对外暴露的名称


